import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useRef, useState } from 'react';
import { GraduationCap, Briefcase, Target, Award } from 'lucide-react';
const About = () => {
    const [isVisible, setIsVisible] = useState(false);
    const sectionRef = useRef(null);
    useEffect(() => {
        const observer = new IntersectionObserver((entries) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    setIsVisible(true);
                }
            });
        }, { threshold: 0.1 });
        if (sectionRef.current) {
            observer.observe(sectionRef.current);
        }
        return () => observer.disconnect();
    }, []);
    return (_jsxs("section", { ref: sectionRef, id: "about", className: "py-24 bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 relative overflow-hidden", children: [_jsxs("div", { className: "absolute inset-0", children: [_jsx("div", { className: "absolute top-20 left-20 w-96 h-96 bg-indigo-500/5 rounded-full blur-3xl" }), _jsx("div", { className: "absolute bottom-20 right-20 w-96 h-96 bg-blue-500/5 rounded-full blur-3xl" })] }), _jsx("div", { className: "absolute inset-0 opacity-[0.02]", children: _jsx("div", { className: "absolute inset-0", style: {
                        backgroundImage: 'linear-gradient(rgba(255, 255, 255, 0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255, 255, 255, 0.1) 1px, transparent 1px)',
                        backgroundSize: '80px 80px'
                    } }) }), _jsx("div", { className: "container mx-auto px-6 relative z-10", children: _jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsxs("div", { className: `mb-16 transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`, children: [_jsxs("div", { className: "inline-flex items-center gap-2 bg-white/5 backdrop-blur-sm border border-white/10 px-4 py-2 rounded-full mb-6", children: [_jsx("div", { className: "w-2 h-2 bg-indigo-400 rounded-full" }), _jsx("span", { className: "text-gray-300 text-sm font-medium", children: "Get to Know Me" })] }), _jsxs("h2", { className: "text-5xl md:text-6xl font-bold text-white mb-4", children: ["About ", _jsx("span", { className: "text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400", children: "Me" })] }), _jsx("div", { className: "w-24 h-1 bg-gradient-to-r from-indigo-500 to-cyan-500 rounded-full" })] }), _jsxs("div", { className: "grid lg:grid-cols-[1.2fr,1fr] gap-12", children: [_jsxs("div", { className: `space-y-8 transition-all duration-1000 delay-200 ${isVisible ? 'opacity-100 translate-x-0' : 'opacity-0 -translate-x-10'}`, children: [_jsxs("div", { className: "bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-8 hover:bg-white/10 transition-all", children: [_jsxs("div", { className: "flex items-center gap-4 mb-6", children: [_jsx("div", { className: "w-12 h-12 bg-gradient-to-br from-indigo-500 to-cyan-500 rounded-xl flex items-center justify-center", children: _jsx(Target, { size: 24, className: "text-white" }) }), _jsx("h3", { className: "text-2xl font-bold text-white", children: "Profile" })] }), _jsx("p", { className: "text-gray-300 leading-relaxed mb-4", children: "I am an Automation Engineering student at Diponegoro University with a strong interest in technology, design, and innovation. My expertise spans UI/UX design and software engineering, combined with hands-on experience in robotics development as part of the Undip Robotics Development Center." }), _jsx("p", { className: "text-gray-300 leading-relaxed", children: "Beyond the technical field, I am also passionate about leadership and event organization, having actively contributed to planning and executing various academic and student activities." })] }), _jsxs("div", { className: "bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-8 hover:bg-white/10 transition-all", children: [_jsxs("div", { className: "flex items-center gap-4 mb-6", children: [_jsx("div", { className: "w-12 h-12 bg-gradient-to-br from-cyan-500 to-blue-500 rounded-xl flex items-center justify-center", children: _jsx(Briefcase, { size: 24, className: "text-white" }) }), _jsx("h3", { className: "text-2xl font-bold text-white", children: "Expertise" })] }), _jsx("div", { className: "grid grid-cols-2 gap-4", children: [
                                                        { icon: '🤖', title: 'Robotics' },
                                                        { icon: '✈️', title: 'UAV Tech' },
                                                        { icon: '⚡', title: 'Electrical' },
                                                        { icon: '🏭', title: 'Manufacturing' },
                                                        { icon: '💻', title: 'UI/UX Design' },
                                                        { icon: '🔧', title: 'SCADA' }
                                                    ].map((item, index) => (_jsxs("div", { className: "bg-white/5 border border-white/10 p-4 rounded-xl hover:bg-white/10 hover:border-indigo-500/50 transition-all", children: [_jsx("div", { className: "text-3xl mb-2", children: item.icon }), _jsx("div", { className: "font-semibold text-white", children: item.title })] }, index))) })] })] }), _jsxs("div", { className: `space-y-8 transition-all duration-1000 delay-400 ${isVisible ? 'opacity-100 translate-x-0' : 'opacity-0 translate-x-10'}`, children: [_jsxs("div", { className: "bg-gradient-to-br from-indigo-600/20 to-cyan-600/20 backdrop-blur-md border border-indigo-500/30 rounded-2xl p-8", children: [_jsxs("div", { className: "flex items-center gap-4 mb-6", children: [_jsx("div", { className: "w-12 h-12 bg-white/10 backdrop-blur-sm rounded-xl flex items-center justify-center", children: _jsx(GraduationCap, { size: 24, className: "text-white" }) }), _jsx("h3", { className: "text-2xl font-bold text-white", children: "Education" })] }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "relative pl-6 border-l-2 border-white/20", children: [_jsx("div", { className: "absolute -left-2 top-0 w-4 h-4 bg-white rounded-full" }), _jsx("div", { className: "text-sm text-indigo-200 mb-2", children: "Aug 2023 - Present" }), _jsx("h4", { className: "text-xl font-bold text-white mb-2", children: "Diponegoro University" }), _jsx("p", { className: "text-gray-200 mb-1", children: "Bachelor of Applied Science" }), _jsx("p", { className: "text-gray-300", children: "Automation Engineering Technology" }), _jsx("div", { className: "mt-3 inline-block bg-white/10 backdrop-blur-sm px-4 py-2 rounded-full text-sm font-semibold text-white", children: "Semester 5" })] }), _jsxs("div", { className: "relative pl-6 border-l-2 border-white/10", children: [_jsx("div", { className: "absolute -left-1.5 top-0 w-3 h-3 bg-white/50 rounded-full" }), _jsx("div", { className: "text-sm text-indigo-200 mb-2", children: "Jun 2020 - Jul 2023" }), _jsx("h4", { className: "text-lg font-bold text-white mb-1", children: "SMA N 8 Semarang" }), _jsx("p", { className: "text-gray-300", children: "Senior High School - Science and Mathematics" })] })] })] }), _jsxs("div", { className: "bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-8 hover:bg-white/10 transition-all", children: [_jsxs("div", { className: "flex items-center gap-4 mb-6", children: [_jsx("div", { className: "w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-500 rounded-xl flex items-center justify-center", children: _jsx(Award, { size: 24, className: "text-white" }) }), _jsx("h3", { className: "text-2xl font-bold text-white", children: "Key Projects" })] }), _jsx("div", { className: "space-y-3", children: [
                                                        'Line Following Robot',
                                                        'Automatic Trash Bin with Arduino',
                                                        'Automatic Soil Watering System',
                                                        'ADC (Analog to Digital Converter)',
                                                        'Full Wave Rectifier Circuit',
                                                        'SCADA System Development',
                                                        'Company Profile Website'
                                                    ].map((project, index) => (_jsxs("div", { className: "flex items-start gap-3 group hover:bg-white/5 p-3 rounded-xl transition-all", children: [_jsx("div", { className: "w-6 h-6 bg-gradient-to-br from-indigo-500 to-cyan-500 rounded-lg flex items-center justify-center flex-shrink-0", children: _jsx("span", { className: "text-white text-xs font-bold", children: index + 1 }) }), _jsx("p", { className: "text-gray-300 font-medium group-hover:text-white transition-colors", children: project })] }, index))) })] })] })] })] }) })] }));
};
export default About;
